version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
      - vscode-server:/home/vscode/.vscode-server
    command: sleep infinity

volumes:
  vscode-server:
